name: "Validate Gradle Wrapper"

on:
  workflow_dispatch:
    # manually run
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3